/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-19 11:45:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kh.member.model.vo.*;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1545213651548L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1544431610007L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.kh.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");

    List<Member> list = (List<Member>)request.getAttribute("list");
    
	int cPage = (int)request.getAttribute("cPage");
	int numPerPage = (int)request.getAttribute("numPerPage");
	String searchType = (String)request.getAttribute("searchType");
	String searchKeyword = (String)request.getAttribute("searchKeyword");
	String pageBar = (String)request.getAttribute("pageBar");

	
	
	
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("   \r\n");

	Member memberLoggedIn = (Member)session.getAttribute("logm");

	//전송된 쿠키확인
	boolean saveId = false;
	String memberId = "";
	
	Cookie[] cookies = request.getCookies();
	//System.out.println("브라우져가 전송한 쿠키 목록@header.jsp");
	//System.out.println("-------------------------------");
	for(Cookie c : cookies){
		String key = c.getName();
		String value = c.getValue();
		
		//System.out.printf("%s = %s\n", key, value);
		if("saveId".equals(key)){
			saveId = true;
			memberId = value; //abcde
			
		}
	}
	//System.out.println("-------------------------------");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function loginValidate(){\r\n");
      out.write("    if($(\"#memberId\").val().trim().length==0){\r\n");
      out.write("        alert(\"아이디를 입력하세요.\");\r\n");
      out.write("        $(\"#memberId\").focus();\r\n");
      out.write("        return false;//폼 전송방지\r\n");
      out.write("    }\r\n");
      out.write("    if($(\"#password\").val().trim().length==0){\r\n");
      out.write("        alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("        $(\"#password\").focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1>Hello MVC</h1>\r\n");
      out.write("            <!--로그인 시작  -->\r\n");
      out.write("            <div class=\"login-container\">\r\n");
      out.write("            ");
if(memberLoggedIn == null) {
      out.write("\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\"\r\n");
      out.write("                method=\"post\"\r\n");
      out.write("                id=\"loginFrm\"\r\n");
      out.write("                onsubmit=\"return loginValidate();\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <input type=\"text\" \r\n");
      out.write("                        \t   name=\"memberId\" \r\n");
      out.write("                        \t   id=\"memberId\" \r\n");
      out.write("                        \t   value = \"");
      out.print(memberId);
      out.write("\"\r\n");
      out.write("                        \t   placeholder=\"아이디\"/></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("                        <td><input type=\"submit\" value=\"로그인\"/></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\">\r\n");
      out.write("                        \t<input type=\"checkbox\" \r\n");
      out.write("                        \t       name=\"saveId\" \r\n");
      out.write("                        \t\t   id=\"saveId\"\r\n");
      out.write("                        \t\t   ");
      out.print(saveId?"checked" : "");
      out.write(">\r\n");
      out.write("                        <label for=\"saveId\">\r\n");
      out.write("                        \t아이디저장\r\n");
      out.write("                        </label>\r\n");
      out.write("                        &nbsp;&nbsp;\r\n");
      out.write("                        <input type=\"button\" \r\n");
      out.write("                        \t   value=\"회원가입\"\r\n");
      out.write("                        \t   onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll'\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 }
            else {
      out.write("\r\n");
      out.write("            \t<table id=\"logged-in\">\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td>\r\n");
      out.write("            \t\t\t\t");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님,\r\n");
      out.write("            \t\t\t\t안녕하세요 :)\r\n");
      out.write("            \t\t\t</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td>\r\n");
      out.write("            \t\t\t\t<input type=\"button\" \r\n");
      out.write("            \t\t\t\t\t   value=\"내정보보기\" \r\n");
      out.write("            \t\t\t\t\t   onclick='location.href = \"");
      out.print(request.getContextPath() );
      out.write("/member/memberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\"' />\r\n");
      out.write("            \t\t\t\t&nbsp;\r\n");
      out.write("            \t\t\t\t<input type=\"button\" \r\n");
      out.write("            \t\t\t\t\t   value=\"로그아웃\" \r\n");
      out.write("            \t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("            \t\t\t</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t</table>\r\n");
      out.write("            \t\r\n");
      out.write("            \t\r\n");
      out.write("            \t\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 로그인 끝 -->\r\n");
      out.write("            <!-- 메인메뉴 시작  -->\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"main-nav\">\r\n");
      out.write("                    <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/boardList\">게시판</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                   \t<!--  관리자인 경우만 보이기 -->\r\n");
      out.write("                   \t");
 if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- 메인메뉴 끝 -->\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <section id=\"content\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/admin.css\" />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar sid = $(\"#search-memberId\");\r\n");
      out.write("\tvar sname = $(\"#search-memberName\");\r\n");
      out.write("\tvar sgender = $(\"#search-gender\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"select#searchType\").change(function(){\r\n");
      out.write("\t\tsid.hide();\r\n");
      out.write("\t\tsname.hide();\r\n");
      out.write("\t\tsgender.hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#search-\"+$(this).val()).css(\"display\",\"inline-block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"memberList-container\">\r\n");
      out.write("\t<h2>회원관리</h2>\r\n");
      out.write("\t<!-- 검색 시작 -->\r\n");
      out.write("\t<div id=\"search-container\">\r\n");
      out.write("\t\t검색 타입 : \r\n");
      out.write("\t\t<select id=\"searchType\">\r\n");
      out.write("\t\t\t<option value=\"memberId\">아이디</option>\r\n");
      out.write("\t\t\t<option value=\"memberName\">회원명</option>\r\n");
      out.write("\t\t\t<option value=\"gender\">성별</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<!-- 아이디 검색폼 -->\r\n");
      out.write("\t\t<div id=\"search-memberId\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/memberFinder\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"numPerPage\"\r\n");
      out.write("\t\t\t\t\t   value=\"");
      out.print(numPerPage);
      out.write("\" />\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchType\"\r\n");
      out.write("\t\t\t\t\t   value=\"memberId\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\"\r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"25\"\r\n");
      out.write("\t\t\t\t\t   placeholder=\"검색할 아이디를 입력하세요.\" />\r\n");
      out.write("\t\t\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-memberName\">\r\n");
      out.write("\t\t<!-- 회원명 검색폼 -->\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/memberFinder\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"numPerPage\"\r\n");
      out.write("\t\t\t\t\t   value=\"");
      out.print(numPerPage);
      out.write("\" />\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchType\"\r\n");
      out.write("\t\t\t\t\t   value=\"memberName\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\"\r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"25\"\r\n");
      out.write("\t\t\t\t\t   placeholder=\"검색할 회원명을 입력하세요.\" />\r\n");
      out.write("\t\t\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-gender\">\r\n");
      out.write("\t\t<!-- 성별 검색폼 -->\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/memberFinder\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"numPerPage\"\r\n");
      out.write("\t\t\t\t\t   value=\"");
      out.print(numPerPage);
      out.write("\" />\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"M\"\r\n");
      out.write("\t\t\t\t\t   id=\"gender0\" />\r\n");
      out.write("\t\t\t\t<label for=\"gender0\">남</label>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"F\"\r\n");
      out.write("\t\t\t\t\t   id=\"gender1\" />\r\n");
      out.write("\t\t\t\t<label for=\"gender1\">여</label>\r\n");
      out.write("\t\t\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 검색 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<table id=\"tbl-member\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t<td>나이</td>\r\n");
      out.write("\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t<td>전화번호</td>\r\n");
      out.write("\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t<td>취미</td>\r\n");
      out.write("\t\t\t\t<td>가입날짜</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t");
 if(list == null || list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"9\" align=\"center\">검색 결과가 없습니다.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
} 
			else {
				for(Member m :list) {
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberView?memberId=");
      out.print(m.getMemberId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(m.getMemberId() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getMemberName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print("M".equals(m.getGender())?"남":"여" );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getAge() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getEmail()!=null?m.getEmail():"" );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getPhone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getAddress() !=null?m.getAddress():"" );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getHobby()!=null?m.getHobby():"" );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m.getEnrollDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"pageBar\">\r\n");
      out.write("\t");
      out.print(pageBar );
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2017. <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
